[package]
name = "actix-web-juniper-react-apollo"
version = "0.0.1"
authors = ["zzy <9809920@qq.com>"]
edition = "2018"

[dependencies]
actix = "^0.8.3"
actix-web = "^1.0.7"
pretty_env_logger = "^0.3.1"
futures = "^0.1.28"
serde = { version = "^1.0.100", features = ["derive"] }
serde_json = "^1.0.40"
juniper = "^0.13.1"
diesel = { version = "^1.4.2", features = ["postgres", "chrono"] }
chrono = "^0.4.9"
dotenv = "^0.14.1"
uuid = { version = "^0.7.4", features = ["serde", "v4"] }
jsonwebtoken = "^6.0.1"
bcrypt = "^0.5.0"
